### ISSUE TITLE
need extend toolbars

### ISSUE THREAD

**Issue by plyusninva** [gergo85/oc-news#28]
Please, extend default editor toolbar. Sometimes it is necessary to change the font size and other parameters.
/models/posts/fields.yaml
example:
```
tabs:
    fields:
...
        content:
            tab: indikator.news::lang.form.content
            type: richeditor
            size: giant
            toolbarButtons: fullscreen|bold|italic|underline|subscript|superscript|fontFamily|fontSize|color|inlineStyle|paragraphStyle|paragraphFormat|align|formatOL|formatUL|outdent|indent|quote|insertHR|insertLink|insertImage|insertVideo|insertAudio|insertFile|insertTable|undo|redo|clearFormatting|selectAll|html
```
See how convenient it is:
![image](https://user-images.githubusercontent.com/25381948/28114647-19341c30-671b-11e7-9ac3-28df7192bdf5.png)
